topics = ['hello', 'variable', 'arithemetic', 'strings', 'input', 'registration', ' math ']
print('We have studied', topics)
print('But I dont understand', topics[5])
print('I only watched ', topics[1:])
print('Although I already learnt ', topics[2:7], 'Last week')
topics[0] = 'DateTime'
print(topics)
topics.append('Lists')
print(topics)
topics.remove('variable')
print(topics)
print(len(topics))
print(topics[1])
print(topics[-1])
print(len(topics))
topics.append(4)
topics.append(False)
topics.append(9)
print(topics)
topics.append(True)
print(topics)
